### PR TITLE
Th2 4625 implement get by page where page is a string

### PR DESCRIPTION
**Pull request by xHacka**

### CODE REVIEW

**Comment by xHacka** [comment]
To use `GetPage` command data_source is needed, that's why _get_urls now takes datasource instead. also for the same reason commands with Page class get properties after executing command.

**Comment by xHacka** [comment]
Unittests not added because commands require data_source, CI test are likely to fail. Simply calling command will not raise error because its not handled in init.

**Review by ConnectDIY — CHANGES_REQUESTED** [review]
Hi,

I added some TODO comments and made slight code refactoring.

1. Resolve, please, TODOs
2. What do you think about moving GetPagesAll inside GetPages ?

**Comment by xHacka** [comment]
1. Todo's resolved.
2. GetPagesAll removed, Changed to GetPages(book_id, all=True)
3. PageNotFound exception is raised during GetPageByName
    - Should exception be in utils.pages or DS lib exceptions?

**Review by ConnectDIY — APPROVED** [review]

**Pull request merged**
